title: Galleries
modelClass: NielsVanDenDries\Gallery\Models\Gallery
list: $/nielsvandendries/gallery/models/gallery/columns.yaml
recordUrl: 'nielsvandendries/gallery/galleries/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
