title: Fotos
modelClass: NielsVanDenDries\Gallery\Models\Fotos
list: $/nielsvandendries/gallery/models/fotos/columns.yaml
recordUrl: 'nielsvandendries/gallery/fotos/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
